services:
  docker-115:
    image: docker-115:36.0.0
    platform: linux/amd64
    build:
      context: .
    container_name: docker-115
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Asia/Shanghai}
      - LC_ALL=${DOCKER_115_LC_ALL:-zh_CN.UTF-8}
      - RDP_USER=${RDP_USER:-abc}
      - RDP_PASSWORD=${RDP_PASSWORD:-abc}
    ports:
      - "3389:3389"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    security_opt:
      - seccomp:unconfined
    shm_size: "1gb"
    restart: unless-stopped
